=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require "uri"

module SwaggerClient
  class NumberApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # This API get users numbers. 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page Page to display
    # @return [nil]
    def numbers_get(api_key, opts = {})
      numbers_get_with_http_info(api_key, opts)
      return nil
    end

    # 
    # This API get users numbers. 
    # @param api_key API Key
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page Page to display
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def numbers_get_with_http_info(api_key, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: NumberApi.numbers_get ..."
      end
      # verify the required parameter 'api_key' is set
      if @api_client.config.client_side_validation && api_key.nil?
        fail ArgumentError, "Missing the required parameter 'api_key' when calling NumberApi.numbers_get"
      end
      # resource path
      local_var_path = "/numbers"

      # query parameters
      query_params = {}
      query_params[:'api_key'] = api_key
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?

      # header parameters
      header_params = {}

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NumberApi#numbers_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
