=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CountryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CountryApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CountryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountryApi' do
    it 'should create an instance of CountryApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CountryApi)
    end
  end

  # unit tests for areacodes_country_code_state_id_get
  # 
  # This API get areacodes . 
  # @param country_code countryCode in the Country
  # @param state_id stateId in the Country
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'areacodes_country_code_state_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for countries_country_code_didgroups_get
  # 
  # This API didgroups countryCode. 
  # @param country_code countryCode in the Country
  # @param did_group_ids didGroupId in the Country
  # @param state_id stateId in the Country
  # @param city_name_pattern cityNamePattern in the Country
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'countries_country_code_didgroups_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for countries_didgroups_did_group_id_provision_post
  # 
  # This API didgroups provision. 
  # @param did_group_id didGroupId in the Country
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'countries_didgroups_did_group_id_provision_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for countries_get
  # 
  # This API get countries. 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'countries_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for states_country_code_get
  # 
  # This API get States . 
  # @param country_code countryCode in the Country
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'states_country_code_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
