=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FaxApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FaxApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FaxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FaxApi' do
    it 'should create an instance of FaxApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FaxApi)
    end
  end

  # unit tests for fax_document_id_costs_get
  # 
  # This API get the cost of a sending fax. 
  # @param api_key API Key
  # @param fax_number Fax Number
  # @param document_id id of the file / document_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fax_document_id_costs_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_get
  # 
  # This API get all fax history. 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit Number of records to return
  # @option opts [String] :page Page to display
  # @return [nil]
  describe 'fax_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_job_id_status_get
  # 
  # This API get the status of the fax. 
  # @param api_key API Key
  # @param job_id id of the fax job
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fax_job_id_status_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for incoming_faxes_get
  # 
  # This API get faxes . 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'incoming_faxes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for incoming_faxes_number_get
  # 
  # This API get faxes  by number. 
  # @param api_key API Key
  # @param number Number in the fax
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'incoming_faxes_number_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for provision_numbers_get
  # 
  # This API get Provision numbers. 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit Limit to display
  # @return [nil]
  describe 'provision_numbers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
