=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FaxApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FaxApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FaxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FaxApi' do
    it 'should create an instance of FaxApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FaxApi)
    end
  end

  # unit tests for fax_document_id_costs_get
  # 
  # This API get the cost of a sending fax. 
  # @param api_key API Key
  # @param fax_number Fax Number
  # @param document_id id of the file / document_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fax_document_id_costs_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_history_get
  # 
  # This API get all fax history. 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :limit Number of records to return
  # @option opts [String] :page Page to display
  # @return [nil]
  describe 'fax_history_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_job_id_status_get
  # 
  # This API get the status of the fax. 
  # @param api_key API Key
  # @param job_id id of the fax job
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'fax_job_id_status_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fax_post
  # 
  # This API send the fax. When we send fax using API, Fax.to send a POST to the Callback URL you specified in https://fax.to/member/api/live. Fax.to send POST data with the following information fax_job_id, status and message. 
  # @param api_key API Key
  # @param fax_number Fax Number
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :document_id Document id. If you want to use existing document you need to specify the document_id
  # @option opts [String] :tsi_number If we want to to change the text or number that appear on &#39;from&#39; or &#39;sender&#39; of the fax
  # @option opts [File] :file PDF file to upload
  # @option opts [Integer] :delete_file Whether to delete file after fax transaction. (put 1 to delete)
  # @return [nil]
  describe 'fax_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
