=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FilesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FilesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilesApi' do
    it 'should create an instact of FilesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FilesApi)
    end
  end

  # unit tests for files_get
  # 
  # This API lists all the files 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'files_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_id_delete
  # 
  # This API deletes a single file. 
  # @param api_key API Key
  # @param id id of the file / document
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'files_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_post
  # 
  # This API allows uploading of a single file. 
  # @param api_key API Key
  # @param file PDF file to upload
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'files_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
