=begin
#Fax.to REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::NumberApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NumberApi' do
  before do
    # run before each test
    @instance = SwaggerClient::NumberApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NumberApi' do
    it 'should create an instance of NumberApi' do
      expect(@instance).to be_instance_of(SwaggerClient::NumberApi)
    end
  end

  # unit tests for numbers_get
  # 
  # This API get users numbers. 
  # @param api_key API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page Page to display
  # @return [nil]
  describe 'numbers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
